### ISSUE TITLE
TheIDE complains missing SurfaceCtrl package although have installed

### ISSUE THREAD

**Issue by erusyd** [Xemuth/SurfaceCtrl#7] opened 2024-03-14 05:03 UTC
Using the latest ultimatepp, copy `SurfaceCtrl_Demo` into `MyApps` folder, open it in TheIDE, it complains
![image](https://github.com/Xemuth/SurfaceCtrl/assets/1529102/ae33d7d4-ca7b-4c3f-a402-5b013cabe8b9)
Although UppHub has installed this package:
![image](https://github.com/Xemuth/SurfaceCtrl/assets/1529102/24f87ded-0309-42c3-af95-40f1150a160b)

**Comment by Xemuth** [comment] 2024-03-21 09:34
Hello Erusyd, 

If you want to copy a package from the UppHub assembly to use it in MyApps assembly (same for any assenbly) you must ensure that assembly reference UppHub assembly in order to resolve all package that come from this on.

Why you want to copy SurfaceCtrl_demo to MyApps Anyway ? ^^

![image](https://github.com/Xemuth/SurfaceCtrl/assets/46812624/ca1500dc-b4d2-468f-95c4-2892101ae84b)

**Comment by erusyd** [comment] 2024-03-22 02:30
I just want to see the features of `SurfaceCtrl`^^. How to open `Assembly setup` and `Nests editor` dialogs? I can't find them. My system is Linux Mint 21.3.
![Peek 2024-03-22 10-26](https://github.com/Xemuth/SurfaceCtrl/assets/1529102/d982f55f-8882-4e65-8ebc-0a642f929d32)

**Comment by erusyd** [comment] 2024-03-22 02:41
I first remove `SurfaceCtrl/SurfaceCtrl` from `SurfaceCtrl_demo`, then try to add package `SurfaceCtrl` into it, but only `Surface` package shows up, but UppHub shows that I've installed `SurfaceCtrl`. I don't know why?
![Peek 2024-03-22 10-37](https://github.com/Xemuth/SurfaceCtrl/assets/1529102/6a760f6e-1630-48a9-b01b-8d4508b4234e)

**Comment by Xemuth** [comment] 2024-03-22 09:05
I see, the problem is UppHub has been designed to be used as assembly like MyApps, uppsrc, reference, etc... The best way you have to experiment uppHub package is to create a uppHub assembly: 
![image](https://github.com/Xemuth/SurfaceCtrl/assets/46812624/ffd495b9-f914-4b93-9fd2-75b4b6c2fc9b)

To do this, you simply have to right click the assembly list when being in the package selection window: 
![image](https://github.com/Xemuth/SurfaceCtrl/assets/46812624/f2ffbc27-fb35-43c0-836e-8dbcb7029e71)


Then you press "New assembly", This window should open:
![image](https://github.com/Xemuth/SurfaceCtrl/assets/46812624/f4daa036-c843-4235-9b3c-aae1610c5809)
Here you can edit the packages nest (i.e the path to all the package you want to include in this assembly).

Since we want to create An UppHub Assembly and UppHub rely on UppFramework: We gonna add Upphub folder to the nest list and we will move it up:
![image](https://github.com/Xemuth/SurfaceCtrl/assets/46812624/4df46c3b-aaeb-47c7-839b-32b689181283)
The fact that UppHub is the first one in list mean TheIDE will lookup for openable project inside this nest. Other will only be here if it have package to resolve.

By pressing Ok and closing Assemby setup window you should see a new Assembly named UppHub in the list. if you click on it you should see SurfaceCtrl_demo package ready to be open and compiled.

Now let's say you want to use the Surface package in a project located in MyApps. You should not just copy past the package since this package may have some dependencies that reside in UppHub folder too. Instead you should add UppHub nest to your MyApps assembly. By doing that. TheIDE will lookup for unknown package in UppHub Folder

**Comment by erusyd** [comment] 2024-03-25 03:21
Thank you very much!

**Closed as completed** 2024-03-25 03:21 UTC
